# ****** Xuewei Tests ******

  # TestGhostMove
  TestGhostMove:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v2

      - name: TestGhostMove
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/TestGhostMove.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostMove
  
  # TestPacManMove
  TestPacManMove:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v2

      - name: TestPacManMove
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/TestPacManMove.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManMove
  
  # TestMapGetLoc
  TestMapGetLoc:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v2

      - name: TestMapGetLoc
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/TestMapGetLoc.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapGetLoc
