# PacMan compilation and JUnit testing workflow

name: PacMan Compile and Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Code compilation job
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Compile the Java code
      - name: Compile code and tests
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
      
  # Run each test (to be completed)

# ***** Sruthi's Tests *****

# TestPacManConsume:

TestPacManConsume:

runs-on: ubuntu-latest
container: openjdk

steps:
- uses: actions/checkout@v2

# Compile the Java code
      - name: TestPacManConsume
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestConsume

# TestGhostAttack:

TestGhostAttack: 

runs-on: ubuntu-latest
container: openjdk

steps:
- uses: actions/checkout@v2

# Compile the Java code
      - name: TestGhostAttack
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestAttack

# TestMapEatCookie:

TestMapEatCookie:

runs-on: ubuntu-latest
container: openjdk

steps:
- uses: actions/checkout@v2

# Compile the Java code
      - name: TestMapEatCookie
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapEatCookie


